---
driver:
  name: vagrant
  
provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
    - "recipe[apt::default]"
    - "recipe[rundeck::node_unix]"
suites:
  - name: server
    run_list:
      - "recipe[rundeck::server]"
      - "recipe[create_chef_dir]"
      - "recipe[rundeck::chef-rundeck]"
    attributes:
      rundeck:
        hostname: 'localhost'
        security_roles: ['superusers', 'run_only_users']
      domain: 'kitchentest'
