---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.4
    run_list:
    - "recipe[apt::default]"
  - name: ubuntu-12.04
    run_list:
    - "recipe[apt::default]"

suites:
  - name: server
    run_list:
      - "recipe[rundeck::server]"
      - "recipe[create_chef_dir]"
      - "recipe[rundeck::chef-rundeck]"
    attributes:
      rundeck:
        hostname: 'localhost:8080'
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080}]
