---
driver:
  name: dokken
  chef_version: 12.15.19

transport:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

provisioner:
  name: dokken

platforms:
  - name: centos-6
    driver:
      image: centos:6.8
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/yum install -y sudo
  - name: centos-7
    driver:
      image: centos:7.2.1511
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN /usr/bin/yum install -y sudo
  - name: ubuntu-14.04
    driver:
      image: ubuntu-upstart:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install -y sudo openssh-client
      run_list:
        - recipe[apt]
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      privileged: true
      pid_one_command: /lib/systemd/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install -y sudo openssh-client
      run_list:
        - recipe[apt]
