---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[rundeck_fixtures]
      - recipe[rundeck::server]
      - recipe[rundeck::chef-rundeck]
    attributes:
      rundeck:
        user_home: '/var/lib/rundeck'
        hostname: localhost
        security_roles:
          - superusers
          - run_only_users
      domain: kitchentest

  - name: better_chef_rundeck
    data_bags_path: "test/integration/default/data_bags"
    run_list:
      - recipe[rundeck_fixtures]
      - recipe[rundeck::server]
      - recipe[rundeck::chef-rundeck]
      - recipe[rundeck_fixtures::chef_zero]
    attributes:
      rundeck:
        better_chef_rundeck: true
        chef_url: http://localhost:8089
        user_home: '/var/lib/rundeck'
        hostname: localhost
        security_roles:
          - superusers
          - run_only_users
      domain: kitchentest
