---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.2
  solo_rb:
    treat_deprecation_warnings_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-7
  # - name: ubuntu-18.04

suites:
# - name: apache
#   run_list:
#     - recipe[test::apache]
# - name: repo
#   run_list:
#     - recipe[test::repository]
- name: server_install
  run_list:
    - recipe[test::server_install]
# - name: better_chef
#   run_list:
#     - recipe[test::better_chef]  