Style/Encoding:
  Enabled: false
LineLength:
  Max: 160
MethodLength:
  Max: 30
FileName:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
ParenthesesAsGroupedExpression:
  Enabled: false
