sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  - SUITE=chefspec
  - SUITE=lint
  - SUITE=centos-6
  - SUITE=centos-7
  - SUITE=ubuntu-1404
  - SUITE=ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script:
  - ./.travis.sh

matrix:
  allow_failures:
    - env: SUITE=lint
    # We are allowing failure for Ubuntu 16. It keeps saying /sbin/status
    # doesn't exist when trying to restart the service rundeckd
    - env: SUITE=ubuntu-1604
  fast_finish: true
